Use `return` instead of `exit` where possible
Not using `return` was an Extreme Portability
habit which I've forgotten the origin of and
so at this point it might be cargo-culted and
I might've been doing it in ways that don't
even in principle improve portability.

Either way, `return` is perfectly portable in
practice today.

Even if it wasn't, that's not a good reason
to not use it. Even if anyone ever actually
used a shell where it didn't work, a basic
search could replace the returns with exits.

In the meantime, it makes the code clearer,
more maintanable and easy to reason about,
allows getting rid of a subshell, and lets
me reuse the current functions more easily.

diff --git a/git-cotree b/git-cotree
--- a/git-cotree
+++ b/git-cotree
@@ -4,73 +4,73 @@
 
 initialize()
 {
-    unused=`git log -n1` || exit 1
-    branch=`git branch --show-current` || exit 1
-    case $branch in '') error_not_on_branch; exit 1; esac
-    root=`git rev-parse --show-toplevel` || exit 1
-    cd "$root" || exit 1
+    unused=`git log -n1` || return 1
+    branch=`git branch --show-current` || return 1
+    case $branch in '') error_not_on_branch; return 1; esac
+    root=`git rev-parse --show-toplevel` || return 1
+    cd "$root" || return 1
     case `git rev-parse --git-common-dir` in .git) :;; *)
-        error_missing_git_directory; exit 1
+        error_missing_git_directory; return 1
     esac
     git diff --staged --quiet
     case $? in 1)
         had_staged_changes=true
-        git commit --quiet --message 'git-cotree temporary commit' || exit 1
+        git commit --quiet --message 'git-cotree temporary commit' || return 1
     esac
-    git config --local core.bare true || exit 1
-    directory=`mktemp -d git-cotree-XXXXXX` || exit 1
-    git worktree add --no-checkout --quiet "$directory" "$branch" || exit 1
+    git config --local core.bare true || return 1
+    directory=`mktemp -d git-cotree-XXXXXX` || return 1
+    git worktree add --no-checkout --quiet "$directory" "$branch" || return 1
     for name in * .*
     do
         case $name in "$directory" | .. | . | .git) :;; *)
-            mv ./"$name" "$directory"/ || exit 1
+            mv ./"$name" "$directory"/ || return 1
         esac
     done
-    cd "$directory" || exit 1
-    git reset --quiet HEAD || exit 1
+    cd "$directory" || return 1
+    git reset --quiet HEAD || return 1
     case $had_staged_changes in true)
-        git reset --soft --quiet HEAD~1 || exit 1
+        git reset --soft --quiet HEAD~1 || return 1
     esac
-    cd "$root" || exit 1
+    cd "$root" || return 1
     case $branch in ?*/*)
-        mkdir -p "${branch%/*}" || exit 1
+        mkdir -p "${branch%/*}" || return 1
     esac
-    git worktree move "$directory" "$branch" || exit 1
+    git worktree move "$directory" "$branch" || return 1
 }
 
 create()
 {
-    case $# in 0) error_need_co_tree; exit 1; esac
-    root=`git rev-parse --git-common-dir`/.. || exit 1
-    root=`cd "$root" && pwd` || exit 1
-    directory=`_resolve_directory "$root" "$1"` || exit 1
+    case $# in 0) error_need_co_tree; return 1; esac
+    root=`git rev-parse --git-common-dir`/.. || return 1
+    root=`cd "$root" && pwd` || return 1
+    directory=`_resolve_directory "$root" "$1"` || return 1
     case $# in 1)
         exec 3>&1
         unused=`git worktree add "$root/$directory" "$directory" 2>&1 1>&3` \
         || git worktree add "$root/$directory" -b "$directory" \
-        || exit 1
-        exit 0
+        || return 1
+        return 0
     esac
-    git worktree add "$root/$directory" -b "$directory" "$2" || exit 1
+    git worktree add "$root/$directory" -b "$directory" "$2" || return 1
 }
 
 delete()
 {
-    case $# in 0) error_need_co_tree; exit 1; esac
-    root=`git rev-parse --git-common-dir`/.. || exit 1
-    root=`cd "$root" && pwd` || exit 1
-    directory=`_resolve_directory "$root" "$1"` || exit 1
-    base=`git -C "$root" branch --show-current` || exit 1
+    case $# in 0) error_need_co_tree; return 1; esac
+    root=`git rev-parse --git-common-dir`/.. || return 1
+    root=`cd "$root" && pwd` || return 1
+    directory=`_resolve_directory "$root" "$1"` || return 1
+    base=`git -C "$root" branch --show-current` || return 1
     branch=`git -C "$root/$directory" branch --show-current 2>/dev/null`
-    git worktree remove $force "$root/$directory" || exit 1
+    git worktree remove $force "$root/$directory" || return 1
     case $branch in "$base") :;; ?*)
-        git branch --delete $force "$branch" || exit 1
+        git branch --delete $force "$branch" || return 1
     esac
     while :
     do
         case $directory in */*)
-            directory=${directory%/*} || exit 1
-            current=`pwd` || exit 1
+            directory=${directory%/*} || return 1
+            current=`pwd` || return 1
             case "$root/$directory" in "$current"/?*)
                 if error=`rmdir "$root/$directory" 2>&1`
                 then
@@ -78,9 +78,9 @@ delete()
                 else
                     if _directory_is_empty "$root/$directory"
                     then
-                        printf '%s\n' "$error" 1>&2; exit 1
+                        printf '%s\n' "$error" 1>&2; return 1
                     fi
-                    exit 0
+                    return 0
                 fi
             esac
         esac
@@ -89,57 +89,57 @@ delete()
 }
 
 _directory_is_empty()
-(
-    cd "$directory" || exit 1
+{
+    cd "$directory" || return 1
     for file in *
     do
-        case $file in '*') :;; *) exit 1; esac
+        case $file in '*') :;; *) return 1; esac
     done
     for file in ?
     do
-        case $file in '?') :;; *) exit 1; esac
+        case $file in '?') :;; *) return 1; esac
     done
     for file in .*
     do
-        case $file in . | ..) :;; *) exit 1; esac
+        case $file in . | ..) :;; *) return 1; esac
     done
-    exit 0
-)
+    return 0
+}
 
 base()
 {
-    case $# in 0) error_need_co_tree; exit 1; esac
-    root=`git rev-parse --git-common-dir`/.. || exit 1
-    root=`cd "$root" && pwd` || exit 1
-    directory=`_resolve_directory "$root" "$1"` || exit 1
-    cd "$root" || exit 1
+    case $# in 0) error_need_co_tree; return 1; esac
+    root=`git rev-parse --git-common-dir`/.. || return 1
+    root=`cd "$root" && pwd` || return 1
+    directory=`_resolve_directory "$root" "$1"` || return 1
+    cd "$root" || return 1
     ref=refs/heads/$directory
     if git show-ref --verify --quiet "$ref"
     then
-        git symbolic-ref HEAD "$ref" || exit 1
-        exit 0
+        git symbolic-ref HEAD "$ref" || return 1
+        return 0
     fi
-    error_not_a_branch "$directory"; exit 1
+    error_not_a_branch "$directory"; return 1
 }
 
 _resolve_directory()
 {
-    directory=${2%/} || exit 1
+    directory=${2%/} || return 1
     while :
     do
         case $directory in ../*)
-            current=`pwd` || exit 1
+            current=`pwd` || return 1
             case $current in "$1"/?*)
-                cd .. || exit 1
+                cd .. || return 1
                 directory=${directory#../}
                 continue
             esac
         esac
         break
     done
-    worktree=`git -C "$previous" rev-parse --is-inside-work-tree` || exit 1
+    worktree=`git -C "$previous" rev-parse --is-inside-work-tree` || return 1
     case $worktree in false)
-        current=`pwd` || exit 1
+        current=`pwd` || return 1
         case $current in "$1"/?*)
             directory=${current#"$1"/}/$directory
         esac
@@ -188,7 +188,7 @@ Options:
     -f --force              force deleting this co-tree
     -D                      short for both --delete and --force
     -b --base               use this co-tree as the base branch
-' || exit 1
+' || return 1
 }
 
 force=
