Fix overbroad error ignore when creating cotrees
When branch "foo" is already checked out in a
worktree, `git worktree add foo foo` will fail
with a different legitimate error that should
end the attempt -- only the "invalid reference"
error warrants falling through to new branch
creation.

diff --git a/git-cotree b/git-cotree
--- a/git-cotree
+++ b/git-cotree
@@ -57,9 +57,13 @@ create()
     root=`find_cotree_root` || return 1
     directory=`_resolve_directory "$root" "$1"` || return 1
     case $# in 1)
-        git worktree add "$root/$directory" "$directory" 2>/dev/null \
-        || git worktree add "$root/$directory" -b "$directory" \
-        || return 1
+        if ! error=`git worktree add "$root/$directory" "$directory" 2>&1`
+        then
+            case $error in 'fatal: invalid reference: '*) :;; *)
+                printf '%s\n' "$error" 1>&2; return 1
+            esac
+            git worktree add "$root/$directory" -b "$directory" || return 1
+        fi
         return 0
     esac
     git worktree add "$root/$directory" -b "$directory" "$2" || return 1
