Add collapsing from cotrees back to normal
    git cotree --collapse <co-tree>

The last major feature necessary for a great
user experience: when you're done with using
multiple worktrees for a while, it's nice to
get back to the default single-worktree
directory layout.

(It also helps interop with scripts/tooling
which can't handle the worktree being/moving
leafwards of the repo root.)

This intentionally allows collapsing even if
there are other things in the repo root. The
ideal solution would probably require a flag
to force allowing an unclean collapse, but
but that's not implemented at this time. For
now this is the minimum viable way to cover
the most common need (to return to normal
when down to one cotree and the repo root is
clean) and not force extra work onto people
who want to f.e. keep at least one worktree
while doing the collapse.

P.S. Have I mentioned that I absolutely hate
Bourne shell file globbing? Profound example
of making a design quirk which caters to a
special case and thus has a shape which is
awkward and is a massive pain in the ass for
almost all serious programmatic use.

diff --git a/git-cotree b/git-cotree
--- a/git-cotree
+++ b/git-cotree
@@ -68,51 +68,10 @@ delete()
         git branch --show-current 2>/dev/null || exit 0
     ` || return 1
     git worktree remove $force "$root/$directory" || return 1
-    current=`pwd` || return 1
-    case "$root/$directory" in "$current"/?*) :;; *)
-        cd "$root" || return 1
-    esac
-    while :
-    do
-        case $directory in */*)
-            directory=${directory%/*}
-            current=`pwd` || return 1
-            case "$root/$directory" in "$current"/?*)
-                if error=`rmdir "$root/$directory" 2>&1`
-                then
-                    continue
-                else
-                    if _directory_is_empty "$root/$directory"
-                    then
-                        printf '%s\n' "$error" 1>&2; return 1
-                    fi
-                    break
-                fi
-            esac
-        esac
-        break
-    done
+    _clean_up_if_cotree_name_had_slashes || return 1
     case $branch in "$base") :;; ?*)
         git branch --delete $force "$branch" || return 1
     esac
-}
-
-_directory_is_empty()
-{
-    cd "$1" || return 1
-    for file in *
-    do
-        case $file in '*') :;; *) return 1; esac
-    done
-    for file in ?
-    do
-        case $file in '?') :;; *) return 1; esac
-    done
-    for file in .*
-    do
-        case $file in . | ..) :;; *) return 1; esac
-    done
-    return 0
 }
 
 base()
@@ -144,6 +103,47 @@ base()
         commit=`git rev-parse HEAD` || return 1
         git -C "$root" update-ref --no-deref HEAD "$commit" || return 1
     esac
+}
+
+collapse()
+{
+    case $# in 0) error_need_co_tree; return 1; esac
+    root=`_find_cotree_root` || return 1
+    directory=`_resolve_directory "$root" "$1"` || return 1
+    cd "$root/$directory" || return 1
+    _in_repository_after_cd "$root" "$directory" || return 1
+    branch=`git branch --show-current` || return 1
+    case $branch in
+    ?*)
+        git -C "$root" symbolic-ref HEAD "refs/heads/$branch" || return 1
+    ;;
+    '')
+        commit=`git rev-parse HEAD` || return 1
+        git -C "$root" update-ref --no-deref HEAD "$commit" || return 1
+    esac
+    temporary=`mktemp -d git-cotree-XXXXXX` || return 1
+    chmod =rwx "$temporary" || return 1
+    for name in * .*
+    do
+        case $name in "$temporary" | .. | . | .git) :;; *)
+            mv ./"$name" "$temporary"/ || return 1
+        esac
+        touch "$temporary/$temporary" "$temporary"/.git || return 1
+    done
+    mv "$temporary" "$root"/ || return 1
+    cd "$root" || return 1
+    git worktree remove --force "$root/$directory" || return 1
+    _clean_up_if_cotree_name_had_slashes || return 1
+    cd "$root/$temporary" || return 1
+    for name in * .*
+    do
+        case $name in "$temporary" | .. | . | .git) :;; *)
+            mv ./"$name" "$root"/ || return 1
+        esac
+    done
+    cd "$root" || return 1
+    rm -r "$temporary" || return 1
+    git config --local core.bare false || return 1
 }
 
 _find_cotree_root()
@@ -218,6 +218,52 @@ _in_repository_after_cd()
     error_outside_repository "$1/$2"; return 1
 }
 
+_clean_up_if_cotree_name_had_slashes()
+{
+    current=`pwd` || return 1
+    case "$root/$directory" in "$current"/?*) :;; *)
+        cd "$root" || return 1
+    esac
+    while :
+    do
+        case $directory in */*)
+            directory=${directory%/*}
+            current=`pwd` || return 1
+            case "$root/$directory" in "$current"/?*)
+                if error=`rmdir "$root/$directory" 2>&1`
+                then
+                    continue
+                else
+                    if _directory_is_empty "$root/$directory"
+                    then
+                        printf '%s\n' "$error" 1>&2; return 1
+                    fi
+                    break
+                fi
+            esac
+        esac
+        break
+    done
+}
+
+_directory_is_empty()
+{
+    cd "$1" || return 1
+    for file in *
+    do
+        case $file in '*') :;; *) return 1; esac
+    done
+    for file in ?
+    do
+        case $file in '?') :;; *) return 1; esac
+    done
+    for file in .*
+    do
+        case $file in . | ..) :;; *) return 1; esac
+    done
+    return 0
+}
+
 error_missing_git_directory()
 {
     printf '%s\n' 'fatal: missing .git directory' 1>&2
@@ -260,6 +306,7 @@ Options:
     -f --force              force deleting this co-tree
     -D                      short for both --delete and --force
     -b --base               set the default base for new co-tree branches
+    -c --collapse           collapse this co-tree into the repo root
 ' || return 1
 }
 
@@ -271,6 +318,7 @@ do
     -h | --help | --usage) help; exit $?;;
     -i | --init | --initialize) action=initialize;;
     -b | --base) action=base;;
+    -c | --collapse) action=collapse;;
     -d | --delete) action=delete;;
     -f | --force) force=--force;;
     -fd | -df | -D) force=--force && action=delete;;
