Improved subdirectory cleanup UX
Make a best-effort attempt to portably and without
error message matching (locales!) detect when an
`rmdir` fails due to the non-issue of other stuff
remaining in the directory, and suppress just that
error message.

Profoundly idiotic and an ethical+intellectual
failing of all responsible that we haven't had
a practically portable `rmdir` flag for that
for the last twenty years or so. How do you care
or think so little about user+dev experience and
error awareness+handling? Spurious non-errors are
noise and at every interface boundary we should
provide a way to unambiguously filter just them
out so that the real errors can be seen/handled.

diff --git a/git-cotree b/git-cotree
--- a/git-cotree
+++ b/git-cotree
@@ -70,12 +70,41 @@ delete()
     do
         case $directory in */*)
             directory=${directory%/*} || exit 1
-            rmdir "$root/$directory" || exit 0
-            continue
+            current=`pwd` || exit 1
+            case "$root/$directory" in "$current"/?*)
+                if error=`rmdir "$root/$directory" 2>&1`
+                then
+                    continue
+                else
+                    if _directory_is_empty "$root/$directory"
+                    then
+                        printf '%s\n' "$error" 1>&2; exit 1
+                    fi
+                    exit 0
+                fi
+            esac
         esac
         break
     done
 }
+
+_directory_is_empty()
+(
+    cd "$directory" || exit 1
+    for file in *
+    do
+        case $file in '*') :;; *) exit 1; esac
+    done
+    for file in ?
+    do
+        case $file in '?') :;; *) exit 1; esac
+    done
+    for file in .*
+    do
+        case $file in . | ..) :;; *) exit 1; esac
+    done
+    exit 0
+)
 
 base()
 {
